### PR TITLE
Move to DotNet 5.0

### PR DESCRIPTION
**Pull request by badcel**

### CODE REVIEW

**Comment by badcel** [comment]
@firox263 @na2axl : Any comments or reservations regarding .NET 5? Can we merge this?

I think we should make use of the most recent technologies as we will probably benefit a lot from it.

**Review by na2axl — APPROVED** [review]
LGTM, I've checked and the modified code looks fine.

**Comment by firox263** [comment]
One small point - Do we want to use `String.Empty` or empty string literals (`""`)? They both compile to the same thing so it's purely a stylistic choice. I like `String.Empty` because it's a bit more readable when you have lots of `+-=?` operators. Thoughts?

Anyhow, looks good to me 👍

**Comment by na2axl** [comment]
According to @firox263 I will be favorable on the usage of `string.Empty` as a code style standard too.

**Comment by badcel** [comment]
I agree with you `string.Empty` is more explicit. I updated the code accordingly. So this could be merged.

**Comment by firox263** [comment]
I think this is ready to merge.

From our discussion in #103, let's merge this first, then check #117 works with it.

**Pull request merged**
