### PR TITLE
ImageSurface: Support memory pressure

### PR DESCRIPTION
**Pull request by badcel**
- [x] I agree that my contribution may be licensed either under MIT or any version of LGPL license.

### CODE REVIEW

**Comment by badcel** [comment]
@cameronwhite Can you take a look here? I'm pretty sure that the code to add memory pressure in `Surface` is incorrect / to low. Can we add some kind of logic to calculate the size in bytes of all supported surfaces?

**Comment by cameronwhite** [comment]
Yeah I think the `width * height` is incorrect since that's the width in pixels, but that doesn't take into account the pixel format (number of bytes per pixel)
I don't think there is actually an API to get a memory usage estimate other than for ImageSurface (which does directly correspond to a memory buffer with a specific pixel format). E.g. some backends like SVG probably don't have a reasonable way to produce this

A general function could check the surface's type (https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-get-type) and then only add memory pressure for ImageSurface? (That's also the only surface type we create in Pinta)
Using width * height could also be a fallback estimate, but I don't know if over-estimating the memory pressure is a bad thing for the GC

**Comment by badcel** [comment]
@cameronwhite I updated the code to only apply memory pressure if we know the size of the image surface and skip the memory pressure in other cases. I think it is better to start as conservative as possible and we can add additional use cases if the need comes up.

Do you think the code is good to go?

**Review by cameronwhite — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
