### PR TITLE
Move GirTool, Integration folders and props files

### PR DESCRIPTION
**Pull request by kashifsoofi**
- [x] I agree that my contribution may be licensed either under MIT or any version of LGPL license.

### CODE REVIEW

**Comment by badcel** [comment]
Thank you for your contribution :+1: 

Some comments:
- The `Integration` project does not show up in the solution `Extensions` folder. Please add it via your ide and remove the project which is still in the wrong place in the solution file, via your ide, too. I don't know why your change does not work. Unfortunately the file format is not very human readable.
- The `GirTool` project does not show up in the solution `Generation` folder. Please add it via your ide and remove the project which is still in the wrong place in the solution file, via your ide, too. I don't know why your change does not work. Unfortunately the file format is not very human readable.
- Please remove the import tags from `GirTool.csproj` as those are already imported via the `Directory.Build.props` file in the `Generation` folder (a warning is shown during compilation):
```XML
  <Import Project="../../Properties/GirCore.Tooling.props" />
  <Import Project="../../Properties/GirCore.Logging.props" />
```
- Please remove the import tags from `Integration.csproj` as those are already imported via the `Directory.Build.props` file in the `Extensions` folder (a warning is shown during compilation):
```XML
  <Import Project="../../Properties/GirCore.Libraries.props" />
  <Import Project="../../Properties/GirCore.Publishing.props" />
```
- You did change some Id from the `FontDialog` sample in the solution file which results in the project being not in the samples folder any more.

**Comment by kashifsoofi** [comment]
I didn't have instant access to Windows machine (Visual Studio), I have now updated using Visual Studio

**Comment by badcel** [comment]
Hm, for some reason the solution file is not working for me with Jetbrains Rider. The `Libs` virtual folder is inside the `Samples` virtual folder. I fixed the file with Rider. Additonally I added a `Properties` virtual folder inside the `SolutionItems` virtual folder. The code is in the following gist: https://gist.github.com/badcel/1d51a74ff50dbb91977d733fb67f16a0

Can you copy the content into your `GirCore.sln` file and verify it works for you?

**Comment by kashifsoofi** [comment]
Tried but build did not work :(

**Comment by badcel** [comment]
I think the solution file is fine now.

Can you try to update the 2 solution filter files? I updated them (there was one project missing in them) and updated the `/` to `\\`.

Gist with the content is here: https://gist.github.com/badcel/a5f9544ffe39ea6bcc5ed91fe0bd0690

**Comment by kashifsoofi** [comment]
Thanks the build passed, can you please check the solution file?

**Comment by badcel** [comment]
Thank you for your contribution :+1:

**Pull request merged**
