### PR TITLE
Release handle exception

### PR DESCRIPTION
**Pull request by badcel**
- [x] I agree that my contribution may be licensed either under MIT or any version of LGPL license.

### CODE REVIEW

**Comment by badcel** [comment]
@cameronwhite: What do you thinkg about this change? It would not crash the application anymore if releasing a handle fails and write to stderror.

**Comment by cameronwhite** [comment]
Adding a log with the type name looks like it would be helpful :+1: 
Is there a chance we'd hit a crash trying to do that though? If releasing the handle hit an AccessViolationException, we might get the same when trying to read the type name from the handle

**Comment by badcel** [comment]
Hm, you are probably right.

**Comment by cameronwhite** [comment]
Maybe instead we can print out the managed object's type which might be safer? The ObjectMapper / ToggleRef seems like it has a handle to the managed object

**Comment by badcel** [comment]
Yeah, I would like to keep the try catch and logging in it's current place. It ensures that 'ReleaseHandle` never fails like the documentation is suggesting.

Accessing the object there is not directly possible. I don't have a good idea on how to refactor:

For example I wouldn't like to cache the type just to have it around in case of an error.

Currently there are like 3 layers: 
- ObjectHandle
- ObjectMapper
- ToggleRef

Perhaps this can be done differently so it gets natural to access the type 🤔

**Comment by badcel** [comment]
Perhaps the ObjectMapper always holds a weak reference to the instance instead of the ToggleRef and the ObjectHandle contains the ToggleRef directly and calls the ObjectMapper.

**Comment by badcel** [comment]
The [docs](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-accessviolationexception#accessviolationexception-and-trycatch-blocks) read like an `AccessViolationException` can't be caught by try/catch blocks.

So this change would potentially not help with https://github.com/PintaProject/Pinta/issues/674

**Comment by badcel** [comment]
This is not the desired fix. The real bug is #1044.

**Pull request closed without merging**
