### PR TITLE
API Coverage: Add Various Methods + Properties

### PR DESCRIPTION
**Pull request by firox263**
This PR adds various methods, properties, etc to Gtk3 and Gdk3.
 - This is enough to port over ExceptionDialog.cs from Hyena.
 - Additional minor changes to WINDOWS.md.

Currently, we don't support defining properties on interfaces. This is needed for things like `GtkOrientable` (see `Orientable.cs`) which is used in boxes. I've temporarily defined it on GtkBox so box is usable, but we should get rid of this sooner rather than later.

### CODE REVIEW

**Comment by firox263** [comment]
Needs to be rebased on `develop` after #94

**Comment by na2axl** [comment]
Hi @firox263, nice work with this, maybe we can continue here to add every other missing properties/method ? If yes I will be able to help 🙂.

For the GInterface problem... I think the only solution to make them support our property model is to convert them to **abstract classes** in C#. I think with abstract class we can achieve the same behavior of a GInterface. What do you think ?

**Comment by badcel** [comment]
@na2axl I think we can't use abstract class for GInterfaces, as a class can implement several interfaces, but not several abstract classes.

I made a test for interfaces with default implementations here: https://github.com/gircore/gir.core/pull/99

**Comment by firox263** [comment]
@na2axl Resolved the conflicts, should be good to merge now. I'll leave it to you to do some stylistic cleanup/reorganisation.

**Pull request merged**
